#!/bin/bash
ks=$(systemctl status keyboard.service | grep "Active:" | awk '{ print $2 } ')
if [ "$ks" = "active" ]; then
  sudo /etc/trabalhator/stop_keyboard.sh > /dev/null 2>&1 &
fi
echo 'Content-type: application/json'
echo ''
echo '{'
echo ' "keyboard": { "status": "inactvating" }'
echo '}'
echo ''
