#!/bin/bash
ks=$(systemctl status keyboard.service | grep "Active:" | awk '{ print $2 }')
ms=$(systemctl status mouse.service | grep "Active:" | awk '{ print $2 }')
keyboard=$(tail -1 /usr/lib/cgi-bin/keyboard.log)
if [ "$keyboard" == "" ]; then
    keyboard=""
else
    keyboard=","$keyboard
fi
mouse=$(tail -1 /usr/lib/cgi-bin/mouse.log)
if [ "$mouse" == "" ]; then
    mouse=""
else
    mouse=","$mouse
fi
echo 'Content-type: application/json'
echo ''
echo '{'
echo ' "keyboard": { "status": "'$ks'" '$keyboard' },'
echo ' "mouse": { "status": "'$ms'" '$mouse' }'
echo '}'
echo ''
d